### ISSUE TITLE
Helium config details?

### ISSUE THREAD

**Issue by gniezen** [bertrik/sensor-data-bridge#5]
Hi @bertrik !

The README mentions experimental support for Helium. How would I go about configuring this?

I'm busy moving my existing sensors back to TTN after our city rolled out a new LoRaWAN deployment, but still have Helium sensors in the field that I'd like to forward to sensor.community as well.

Thanks for all your efforts!

**Comment by bertrik** [comment]
The Helium support was more-or-less abandoned. I wasn't really sure if Helium was going anywhere, staying a kind of crypto-only thing only or becoming an actual data transfer platform. I haven't looked at it in years and removed part of the code. 

I'm open to revive it if it helps you. I should have another look if the data format is still the same.

What makes TheThingsNetwork so much easier to use is that I can just connect to *their* server and grab the data, and there's no need for the program to have a TCP port open and wait for external data to be pushed, configure an incoming port in the firewall etc.

**Comment by gniezen** [comment]
Oh, never mind. Sounds like it will be easier for me to just go and update the Helium sensors to use TTN instead.

**Comment by bertrik** [comment]
Oh, and one more thing: for TTN I'm now using their device attribute system. So at TheThingsNetwork you can assign each device a list of custom attributes. One of them can be "senscom-id", which is the id by which it that particular node is known at sensor.community and that is used to upload data. I looked again at the Helium console and couldn't find a similar mechanism.

Looking back at the code, I see that I wrote the initial Helium support to use the Helium mqtt mechanism, so that part is actually quite similar to how TTN works, except you need to have a public mqtt server somewhere to publish data from Helium.
